name: Library ON Push & PR DO Code check
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Check Flutter SDK version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Dart Code Metrics
        uses: solid-software/dart-code-metrics-action@bb6c6b9b92f6adbd2b77fd83747a85f1f1be17ca
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fatal_warnings: true
          fatal_style: true
          folders: "lib"

      - name: Check formatting
        run: dart format . --set-exit-if-changed

      - name: Run tests
        run: |
          # run tests if `test` folder exists
          if [ -d test ]
          then
              flutter test -r expanded
          else
              echo "Tests not found."
          fi
